name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment : development

    steps:
      - uses: actions/checkout@v2

      - name: az cli login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: terraform init
        id: init
        run: terraform init

      - name: terraform plan
        id: plan
        run: terraform plan