name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment : development
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - uses: actions/checkout@v2

      # - name: az cli login
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1

      - name: Download Go Modules
        working-directory: tests
        run: go mod download

      # - name: Run Go Tests
      #   working-directory: tests
        #run: go test -timeout 99999s
        #run: gotestsum --format short-verbose -- -timeout 99999s
      - name: Setup gotestsum
        uses: autero1/action-gotestsum@v0.1.0
        with:
          gotestsum_version: 0.4.1
      - name: Interact with gotestsum
        working-directory: tests
        run: gotestsum --format short-verbose