name: validate

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    environment : development
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - uses: actions/checkout@v2

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: terraform init
        run: terraform init

      - name: terraform validate
        run: terraform validate

      - name: terraform fmt
        run: terraform fmt -check -recursive
        continue-on-error: false

      - name: setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: fetch go modules
        working-directory: tests
        run: go mod download

      - name: run tests
        working-directory: tests
        run: go test -timeout 99999s